//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 私享家架构设计
//  @ File Name : MemberEntity.java
//  @ Date : 2014/8/11
//  @ Author : 
//
//

package com.sxj.supervisor.entity.member;

import java.io.Serializable;
import java.util.Date;

import com.sxj.mybatis.pagination.Pagable;

public class MemberEntity  extends Pagable implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 8851524763229466282L;

	/**
	 * 标识
	 **/
	private String id;

	/**
	 * 会员名称
	 **/
	private String name;

	/**
	 * 营业执照号
	 **/
	private String bLicenseNo;

	/**
	 * 会员类型
	 **/
	private Integer type;

	/**
	 * 地理区域
	 **/
	private String area;

	/**
	 * 联系人名称
	 **/
	private String contacts;

	/**
	 * 节能标识号
	 **/
	private String energyNo;

	/**
	 * 联系人手机
	 **/
	private String phoneNo;

	/**
	 * 公司地址
	 **/
	private String address;

	/**
	 * 联系电话
	 **/
	private String telNum;

	/**
	 * 注册日期
	 **/
	private Date regDate;

	/**
	 * 认证日期
	 **/
	private Date authorDate;

	/**
	 * 账户状态
	 **/
	private Integer state;

	/**
	 * 审核状态
	 **/
	private Integer checkState;

	/**
	 * 总交易额
	 **/
	private Long totalAmount;

	/**
	 * 子账户数目
	 **/
	private Integer accountNum;

	/**
	 * 会员密码
	 **/
	private String password;

	/**
	 * 会员号
	 **/
	private String memberNo;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getbLicenseNo() {
		return bLicenseNo;
	}

	public void setbLicenseNo(String bLicenseNo) {
		this.bLicenseNo = bLicenseNo;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getContacts() {
		return contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	public String getEnergyNo() {
		return energyNo;
	}

	public void setEnergyNo(String energyNo) {
		this.energyNo = energyNo;
	}

	public String getPhoneNo() {
		return phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelNum() {
		return telNum;
	}

	public void setTelNum(String telNum) {
		this.telNum = telNum;
	}

	public Date getRegDate() {
		return regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public Date getAuthorDate() {
		return authorDate;
	}

	public void setAuthorDate(Date authorDate) {
		this.authorDate = authorDate;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getCheckState() {
		return checkState;
	}

	public void setCheckState(Integer checkState) {
		this.checkState = checkState;
	}

	public Long getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(Long totalAmount) {
		this.totalAmount = totalAmount;
	}

	public Integer getAccountNum() {
		return accountNum;
	}

	public void setAccountNum(Integer accountNum) {
		this.accountNum = accountNum;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMemberNo() {
		return memberNo;
	}

	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo;
	}

}